// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkUVakKKYDKXIonvb_0lT_wwyklhOfv9M',
    appId: '1:484824323293:web:7267f4d93c32842645b734',
    messagingSenderId: '484824323293',
    projectId: 'watering-98bbb',
    authDomain: 'watering-98bbb.firebaseapp.com',
    databaseURL: 'https://watering-98bbb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'watering-98bbb.appspot.com',
    measurementId: 'G-GXJ0WJLJF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAT1zg85-cxwCdSEjbusS8oFkRdGtfZN8',
    appId: '1:484824323293:android:3565fedfa182710145b734',
    messagingSenderId: '484824323293',
    projectId: 'watering-98bbb',
    databaseURL: 'https://watering-98bbb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'watering-98bbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Mhq_AEvTCNREl2nCHZ8EAntMvsBDmyA',
    appId: '1:484824323293:ios:0c66fdff9a801b8045b734',
    messagingSenderId: '484824323293',
    projectId: 'watering-98bbb',
    databaseURL: 'https://watering-98bbb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'watering-98bbb.appspot.com',
    iosBundleId: 'com.example.embeddingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5Mhq_AEvTCNREl2nCHZ8EAntMvsBDmyA',
    appId: '1:484824323293:ios:267cb07051d28d7a45b734',
    messagingSenderId: '484824323293',
    projectId: 'watering-98bbb',
    databaseURL: 'https://watering-98bbb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'watering-98bbb.appspot.com',
    iosBundleId: 'com.example.embeddingApp.RunnerTests',
  );
}
